### ISSUE TITLE
Fixing Account Page

### ISSUE THREAD

**Issue by a-box31** [a-box31/ABlog#12]
- [x] first update the account page api calls to get the user's account information
- [x] next edit the account page such that a user can update their avatar and bio
- [x] then ensure the other settings work on the account page, such as deleting the account and logging out.  
- [ ] finally add the blogs into the blog page by making reference to the getUserBlogs api
- [ ] also create an editor for the blogs so the user can update the blogs in the account page

**Comment by Anyidollar** [comment]
Hi, should I take this up?
