### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by a-box31** [a-box31/ABlog#16]
- [ ] Add code documentation
- [ ] Add api layer documentation to the readme
- [ ] There should be two separations. One for the front-end and the other for the backend
- [ ] front end documentation should list all the features of the app
- [ ] backend documentation should list all the app's api's as well as document and chart the mySQL database tables

**Comment by fduffoo** [comment]
Hey there, I can help with this if you can assign it to me

**Comment by a-box31** [comment]
I assigned the issue to you.
